### ISSUE TITLE
java.net.ProtocolException: Too many follow-up requests: 21

### ISSUE THREAD

**Issue by Anton111111** [mattbdean/JRAW-Android#4]
I try to use JRAW-Android.
But when i try to use userless auth i get error: 

> java.net.ProtocolException: Too many follow-up requests: 21
>         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:175)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
>         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
>         at okhttp3.RealCall.execute(RealCall.java:92)
>         at net.dean.jraw.http.OkHttpNetworkAdapter.execute(OkHttpNetworkAdapter.kt:16)
>         at net.dean.jraw.oauth.OAuthHelper.applicationOnlyOAuthData$lib(OAuthHelper.kt:88)
>         at net.dean.jraw.oauth.OAuthHelper.automatic(OAuthHelper.kt:30)
>         at net.dean.jraw.oauth.AccountHelper.switchToUserless(AccountHelper.kt:74)
>         at com.appdev.sample.MainActivity.lambda$onCreate$0(MainActivity.java:62)
>         at com.appdev.sample.-$$Lambda$MainActivity$J9amhYO4FFQm29Usa1UsDVS3GoE.call(Unknown Source:2)
>         at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
>         at io.reactivex.Single.subscribe(Single.java:3575)
>         at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
>         at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
>         at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
>         at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)

This my code to show how i use JRAW-Android:

```
AppInfoProvider provider = new ManifestAppInfoProvider(getApplicationContext());
        UUID deviceUuid = UUID.randomUUID();
        // Store our access tokens and refresh tokens in shared preferences
        tokenStore = new SharedPreferencesTokenStore(getApplicationContext());
        // Load stored tokens into memory
        tokenStore.load();
        // Automatically save new tokens as they arrive
        tokenStore.setAutoPersist(true);
        // An AccountHelper manages switching between accounts and into/out of userless mode.
        accountHelper = AndroidHelper.accountHelper(provider, deviceUuid, tokenStore);

        Disposable disposable = Single.fromCallable(() -> accountHelper.switchToUserless())
                .subscribeOn(Schedulers.io())
                .subscribe(rc -> {
                    LogAdapter logAdapter = new SimpleAndroidLogAdapter(Log.INFO);
                    redditClient = rc;
                    redditClient.setLogger(
                            new SimpleHttpLogger(SimpleHttpLogger.DEFAULT_LINE_LENGTH, logAdapter));
                }, throwable -> Log.e("!!!", "!!!Error", throwable));
```
And part of my manifest:

```
<meta-data
            android:name="net.dean.jraw.android.REDDIT_USERNAME"
            android:value="Test" />
        <meta-data
            android:name="net.dean.jraw.android.CLIENT_ID"
            android:value="com.appdev.redditapiwrapper.sample" />
        <meta-data
            android:name="net.dean.jraw.android.REDIRECT_URL"
            android:value="" />
```

What's i do wrong?

**Comment by Anton111111** [comment]
Issue can be closed. I used not correct client id
